# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
warnings_are_errors: true
sudo: true


addons:
    apt:
        packages:
            - libudunits2-dev
            - libnetcdf-dev
            - netcdf-bin

matrix:
    include:
        - os: linux
          r: release
          dist: trusty # 14.04
          env:
           - BUILD_NAME=trusty_release
           - DETAILS="release build"


# r-devel temporarily switched off; see
# https://www.mail-archive.com/r-devel@r-project.org/msg38248.html

notifications:
  email:
    on_success: change
    on_failure: change

#r_github_packages:
#      - jimhester/covr


after_success:
  - Rscript -e 'covr::codecov()'

