# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
warnings_are_errors: true
sudo: false
cache: packages


addons:
    apt:
        packages:
            - libudunits2-dev
            - libnetcdf-dev
            - netcdf-bin

matrix:
    include:
        - os: linux
          r: release
          dist: trusty # 14.04
          env:
           - BUILD_NAME=trusty_release
           - DETAILS="release build"
        - os: linux
          r: devel
          dist: trusty
          env:
           - BUILD_NAME=trusty_devel
           - DETAILS="devel build"
        - os: linux
          r: oldrel
          dist: trusty
          env:
           - BUILD_NAME=trusty_oldrel
           - DETAILS="oldrel build"
        - os: osx
          r: oldrel
          env:
           - BUILD_NAME=osx_oldrel
           - DETAILS="oldrel build"
        - os: osx
          r: release
          env:
           - BUILD_NAME=osx_release
           - DETAILS="release build"
        - os: osx
          r: devel
          env:
           - BUILD_NAME=osx_devel
           - DETAILS="devel build"

# r-devel temporarily switched off; see
# https://www.mail-archive.com/r-devel@r-project.org/msg38248.html

notifications:
  email:
    on_success: change
    on_failure: change

#r_github_packages:
#      - jimhester/covr


after_success:
  - Rscript -e 'covr::codecov()'

